name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --silent || npm run lint

      - name: Type check
        run: npm run type-check --silent || echo "skip type-check"

      - name: Build
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
          # 공개 키들은 빌드 타임에 필요할 수 있어 secrets 로 주입 (레포 Settings > Secrets > Actions)
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build --silent || npm run build


